apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend-svc
  name: frontend-svc
spec:
  ports:
  - name: "8100"
    port: 80
    protocol: TCP
  selector:
    app: frontend
#  type: LoadBalancer    
